<a href="https://colab.research.google.com/github/gowtham-dd/Data-Science-Basics/blob/main/DataEngneering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The pandas library in Python is named after the term "Panel Data", which refers to multi-dimensional structured datasets commonly used in statistics and econometrics. The name was chosen to reflect its primary focus on handling and analyzing structured data efficiently.

Additionally, "pandas" also resembles the word "Python data analysis", reinforcing its purpose in data manipulation and analysis. The cute association with the panda bear is just a coincidence! 🐼

What is PySpark? 🔥🐍
PySpark is the Python API for Apache Spark, an open-source distributed computing system. It enables big data processing and machine learning on massive datasets across multiple nodes using parallel computing.

What is RDD (Resilient Distributed Dataset)? ⚡
RDD is the fundamental data structure in Spark. It is an immutable, distributed collection of objects that can be processed in parallel.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
import pandas as pd
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(a)
print(a[::-1])
print(a['a':'e':2])

a    1
b    2
c    3
d    4
e    5
dtype: int64
e    5
d    4
c    3
b    2
a    1
dtype: int64
a    1
c    3
e    5
dtype: int64

In [14]:
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(a)
print(a+10)
print(a-10)
print(a*10)
print(a/10)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    11
b    12
c    13
d    14
e    15
dtype: int64
a   -9
b   -8
c   -7
d   -6
e   -5
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64
a    0.1
b    0.2
c    0.3
d    0.4
e    0.5
dtype: float64

In [15]:
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(a)
print(a>3)
print(a>5)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool
a    False
b    False
c    False
d    False
e    False
dtype: bool

In [19]:
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(a)

print(a.apply(lambda x: 'even' if x % 2 == 0 else 'odd'))

a    1
b    2
c    3
d    4
e    5
dtype: int64
a     odd
b    even
c     odd
d    even
e     odd
dtype: object

In [25]:
a=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.std())#standard deviation
print("***************************")
print(a.describe())
print(a.unique())
print(a.value_counts())
print(a.sort_values())

a    1
b    2
c    3
d    4
e    5
dtype: int64
15
3.0
1
5
1.5811388300841898
***************************
count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64
[1 2 3 4 5]
1    1
2    1
3    1
4    1
5    1
Name: count, dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [27]:
b=pd.Series([5,4,6,2,7,1,7],index=['a','b','c','d','e','f','g'])
print(b.cumsum())
print("#################")#5,5+4,5+4+6,5+4+6+2.......
print(b.cummax())#5>4,5>6,6>2,6>7,7>1,7>7
print("#################")
print(b.cummin())
print("#################")
print(b.cumprod())#5,5*4,20*

a     5
b     9
c    15
d    17
e    24
f    25
g    32
dtype: int64
#################
a    5
b    5
c    6
d    6
e    7
f    7
g    7
dtype: int64
#################
a    5
b    4
c    4
d    2
e    2
f    1
g    1
dtype: int64
#################
a        5
b       20
c      120
d      240
e     1680
f     1680
g    11760
dtype: int64

In [31]:
c=pd.Series([3,6,1,7,3,9,2,70], )
print(c.idxmax())
print(c.idxmin())

7
2

DATA FRAMES 2d

In [32]:
#extract data from various file
import pandas as pd
files=pd.read_excel('/content/Student-Employability-Datasets.xlsx')
display(files)

,Name of Student,GENERAL APPEARANCE,MANNER OF SPEAKING,PHYSICAL CONDITION,MENTAL ALERTNESS,SELF-CONFIDENCE,ABILITY TO PRESENT IDEAS,COMMUNICATION SKILLS,Student Performance Rating,CLASS
0,Student 1,4,5,4,5,5,5,5,5,Employable
1,Student 2,4,4,4,4,4,4,3,5,Employable
2,Student 3,4,3,3,3,3,3,2,5,LessEmployable
3,Student 4,3,3,3,2,3,3,3,5,LessEmployable
4,Student 5,4,4,3,3,4,4,3,5,Employable
...,...,...,...,...,...,...,...,...,...,...
2977,Student 2996,4,3,3,3,3,3,2,5,Employable
2978,Student 2997,3,4,4,4,4,4,4,5,Employable
2979,Student 2998,4,5,4,5,4,4,4,5,Employable
2980,Student 2999,4,4,4,3,4,4,3,5,LessEmployable
2981,Student 3000,4,4,4,4,3,4,4,5,Employable

In [33]:
e=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/refs/heads/main/Data1.csv")
display(e)

,studentID,score_exam1,score_exam2,num_total_activities,num_exams,num_activity1,num_activity2,num_activity3,num_activity4
0,1,154,154,7,2,4,1,0,0
1,2,156,156,4,1,0,2,1,0
2,3,151,161,29,2,14,5,4,1
3,4,140,146,83,3,28,7,6,6
4,5,146,146,13,1,11,1,0,0
...,...,...,...,...,...,...,...,...,...
995,996,145,145,63,1,40,8,6,3
996,997,156,156,3,1,0,0,0,2
997,998,156,158,48,4,33,6,2,0
998,999,144,144,14,1,10,2,1,0
999,1000,148,152,7,2,0,2,2,0

In [34]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.5 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [38]:
import pymysql
import pandas as pd

# Database Configuration
DB_HOST = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
DB_USER = "4PFhDQQc2yhfCUH.root"
DB_PASSWORD = "tzNB9UAMnXNidi62"
DB_NAME = "sampleTable"
PORT = 4000
TABLE_NAME = "guvi1.aadhardetails"

try:
    # Step 1: Connect to MySQL Database with SSL
    connection = pymysql.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME,
        port=PORT,  # Specify port
        ssl_verify_cert = True,
        ssl_verify_identity = True,
    )

    print("✅ Successfully connected to the database with SSL.")

    # Step 2: Create a Cursor and Execute SQL Query
    with connection.cursor() as cursor:
        sql_query = f"SELECT * FROM {TABLE_NAME};"
        cursor.execute(sql_query)

        # Step 3: Fetch Data
        result = cursor.fetchall()

    # Step 4: Store Data in a Pandas DataFrame
    df = pd.DataFrame(result)

    # Step 5: Save Data to JSON
    df.to_json("database_output.json", orient="records", indent=4)
    print("✅ Data saved to 'database_output.json'.")

except pymysql.MySQLError as e:
    print(f"❌ Error connecting to MySQL: {e}")

finally:
    # Step 6: Close Connection
    try:
        if connection:
            connection.close()
            print("🔌 MySQL connection closed.")
    except NameError:
        print("⚠ No connection was established, so nothing to close.")

✅ Successfully connected to the database with SSL.
✅ Data saved to 'database_output.json'.
🔌 MySQL connection closed.

In [39]:
display(df)

         0           1         2
0  nethaji  coimbatore  12345678